### PR TITLE
Add merging multiple xccovreport

### PR DESCRIPTION
**Pull request by mininny**
Issue: Using xcov with multiple test targets within one scheme only generates the result of the last test instead of the combined result of all the targets.

Because xcov currently uses only latest coverage and basically overwrites the previous tests, having multiple coverage reports wouldn't even work. So, we should use `xcrun xccov merge` to merge coverage reports and use them to generate output instead. 

In `process_xcresults`, we take `parser.export_xccovreport/archive` and rename them because I've noticed that parser generates files with name `action_0`. But if there are multiple xccovreports in xcresult_paths, they will all get overwritten as `action_0`. When there are multiple results, we merge them and save them to `output_path/out.xccovreport` and return that as the result, otherwise just return the usual result array.

I'm not well acquainted with ruby and xcov's design, so if there's problem, please lmk. 

This PR is inspired by [this previous PR](https://github.com/fastlane-community/xcov/pull/164), but due to its inactivity and because it wasn't working, I created new PR.

### CODE REVIEW

**Comment by CorbinMontague** [comment]
Any update on this PR? It looks like there are 3 outstanding PRs all trying to fix this same issue. The other ones did not fix the issue for me, but this one did, so I'd love to see this get merged.

**Comment by mininny** [comment]
Hi @CorbinMontague, thanks for raising the issue. I think this is caused by xcov's previous bug on calculating the coverage percentage. It seems like it was [fixed few months ago](https://github.com/fastlane-community/xcov/commit/58bee71c6d34baaa475323541bd1bc5ed56999c7), after I committed the last change. I will rebase this PR and hopefully it will work again! 😄

**Comment by CorbinMontague** [comment]
@mininny Thanks for the quick update, that definitely fixed it! Now if only we could get a contributor to review this and help get this into the next xcov release 😉

**Review by joshdholtz — APPROVED** [review]
This looks great! Thanks so much for making this fix ❤️ My apologies on slow review 😔  I will improve my processes

**Comment by joshdholtz** [comment]
Release in https://github.com/fastlane-community/xcov/releases/tag/v1.7.5

Thanks so much for this fix!

**Pull request merged**
