### PR TITLE
Add support for Package.swift derived projects

### PR DESCRIPTION
**Pull request by Coledunsby**

### CODE REVIEW

**Comment by H2wk** [comment]
Looks like this solves the issue listed [here](https://github.com/fastlane-community/xcov/issues/190). Would be great to get this merged in!

**Comment by mathaeus** [comment]
@joshdholtz would anything speak against having this merged and released? :)

**Comment by ridvank** [comment]
It would be nice to hear if there is any updates about this topic. Thanks for the great effort!

**Comment by ridvank** [comment]
@joshdholtz Is there any concern for this pr not to merge?

**Comment by bfernandesbfs** [comment]
Hey , we can approve this ? It’s really important and this branch is since November 20!

**Comment by AttiaMo** [comment]
it would be great of we can hear something about this, it's almost 1 year.
Thanks 🙏

**Comment by pgawlowski** [comment]
Anyone alive here?

**Comment by joshdholtz** [comment]
Will look into things in the next few days!

**Comment by pgawlowski** [comment]
Great! Thank you @joshdholtz !

**Comment by pgawlowski** [comment]
@joshdholtz  - any progress?

**Comment by joshdholtz** [comment]
Looking into this right now 😊

**Review by joshdholtz — APPROVED** [review]
This looks great! Thank you so much 😊

**Pull request merged**
